services:
  frontend:
    build:
      context: .
      args:
        BACKEND_URL: ${BACKEND_URL}
    container_name: transcend-frontend
    env_file:
      - .env
    # environment:
    #   - BACKEND_URL=http://transcend-backend:5000
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  default:
    name: transcend-net
    driver: bridge