services:
  frontend:
    build:
      context: .
      args:
        BACKEND_URL: ${BACKEND_URL}
    container_name: transcend-frontend
    env_file:
      - .env
    restart: unless-stopped

networks:
  default:
    name: transcend-net
    driver: bridge