services:
  frontend:
    build: .
    container_name: transcend-frontend
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  default:
    name: transcend-net
    driver: bridge