include .env
-include .env.local
include ./../infra/.env
export BACKEND_URL

PRETTIER = npx prettier

.PHONY: up generate install build

up: generate install build
	@npm run dev

install:
	@npm install

ci:
  @npm ci

generate: 
	@mkdir -p app/types
	@NODE_TLS_REJECT_UNAUTHORIZED=0 ./node_modules/.bin/openapi-typescript $(CODEGEN_URL)/api-docs -o app/types/api.d.ts
	@NODE_TLS_REJECT_UNAUTHORIZED=0 BACKEND_URL=$(CODEGEN_URL) node scripts/generate-asyncapi.mjs

build:
	@npm run build

.PHONY: lint format check clean fclean re

lint:
	@npm run lint

format:
	@$(PRETTIER) --write "./**/*.{ts,tsx,css}"

check:
	@$(PRETTIER) --check "./**/*.{ts,tsx,css}"
	@npm run lint

clean:
	@rm -rf .next

fclean: clean
	@rm -rf app/types/api.d.ts app/types/asyncapi.d.ts node_modules

re: fclean all