.PHONY: build up down clean
include .env
include ./../infra/.env

build:
	${COMPOSE} -f app-compose.yml build

up:
	${COMPOSE} -f app-compose.yml up -d

down:
	${COMPOSE} -f app-compose.yml down

clean:
	${COMPOSE} -f app-compose.yml down -v
