.PHONY: build up down clean generate
include .env
include ./../infra/.env

node_modules:
	npm ci

app/types/api.d.ts: node_modules
	npm run generate:api:dev

generate: node_modules
	npm run generate:api:dev

build: app/types/api.d.ts
	${COMPOSE} -f app-compose.yml build

up: app/types/api.d.ts
	${COMPOSE} -f app-compose.yml up -d

down:
	${COMPOSE} -f app-compose.yml down

clean:
	${COMPOSE} -f app-compose.yml down -v
	rm -f app/types/api.d.ts
