services:
  backend:
    container_name: transcend
    build:
      context: .
      dockerfile: transcend/Dockerfile
    ports:
      - "5001:5000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - HOST=${HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

networks:
  default:
    external: true
    name: postgres_app_network