include .env
.PHONY: run build format test docs
PROFILE := local

run:
	${GRADLE} bootRun --args='--spring.profiles.active=$(PROFILE)'

build:
	${GRADLE} build

format:
	${GRADLE} spotlessApply

test:
	${GRADLE} jacocoTestReport

docs:
	${GRADLE} docs