.PHONY: build up down drop
PROJECT_NAME = transcend
VERSION = 1.0.0

build:
	${COMPOSE} -f app-compose.yml build --no-cache

up:
	${COMPOSE} -f app-compose.yml up -d

down:
	${COMPOSE} -f app-compose.yml down

drop:
	${COMPOSE} -f app-compose.yml down -v