.PHONY: build up down clean test
include .env
include ./../infra/.env
VERSION = 1.0.0

build:
	${COMPOSE} -f app-compose.yml build --no-cache

up:
	${COMPOSE} -f app-compose.yml up -d

down:
	${COMPOSE} -f app-compose.yml down

clean:
	${COMPOSE} -f app-compose.yml down -v

test:
	${COMPOSE} -f app-compose.yml up --build backend-test --abort-on-container-exit