.PHONY: build up down drop
PROJECT_NAME = transcend
include .env
VERSION = 1.0.0

build:
	${COMPOSE} -f app-compose.yml build --no-cache

up:
	${COMPOSE} -f app-compose.yml up -d

down:
	${COMPOSE} -f app-compose.yml down

drop:
	${COMPOSE} -f app-compose.yml down -v

test:
	docker compose -f app-compose.yml up --build backend-test --abort-on-container-exit