.PHONY: build up down clean test
include .env
include ./../infra/.env

up:
	${COMPOSE} -f app-compose.yml up -d

build:
	${COMPOSE} -f app-compose.yml build --no-cache

down:
	${COMPOSE} -f app-compose.yml down

clean:
	${COMPOSE} -f app-compose.yml down -v

test:
	${COMPOSE} -f app-compose.yml up --build backend-test --abort-on-container-exit