/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * https://docs.gradle.org/8.5/userguide/building_swift_projects.html
 * https://docs.gradle.org/current/userguide/platforms.* html#sub::toml-dependencies-format
*/

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
}

rootProject.name = "backend"
include("transcend")