services:
  db:
    build:
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    container_name: postgres-db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  pgdata:
    driver: local

networks:
  default:
    name: transcend-net
    driver: bridge