/**
 * This file was auto-generated by @asyncapi/modelina.
 * Do not make direct changes to the file.
 */
/* eslint-disable @typescript-eslint/no-explicit-any */

type HeadersNotDocumented = Map<string, any>;

type SpringStompDefaultHeaders = Map<string, any>;

type DeleteMessageRequest = Map<string, any>;

class SendMessageRequest {
  private _content?: string;
  private _additionalProperties?: Map<string, any>;

  constructor(input: {
    content?: string;
    additionalProperties?: Map<string, any>;
  }) {
    this._content = input.content;
    this._additionalProperties = input.additionalProperties;
  }

  get content(): string | undefined {
    return this._content;
  }
  set content(content: string | undefined) {
    this._content = content;
  }

  get additionalProperties(): Map<string, any> | undefined {
    return this._additionalProperties;
  }
  set additionalProperties(additionalProperties: Map<string, any> | undefined) {
    this._additionalProperties = additionalProperties;
  }
}

class CheckPresenceRequest {
  private _userId?: string;
  private _additionalProperties?: Map<string, any>;

  constructor(input: {
    userId?: string;
    additionalProperties?: Map<string, any>;
  }) {
    this._userId = input.userId;
    this._additionalProperties = input.additionalProperties;
  }

  get userId(): string | undefined {
    return this._userId;
  }
  set userId(userId: string | undefined) {
    this._userId = userId;
  }

  get additionalProperties(): Map<string, any> | undefined {
    return this._additionalProperties;
  }
  set additionalProperties(additionalProperties: Map<string, any> | undefined) {
    this._additionalProperties = additionalProperties;
  }
}

class MessageHeaders {
  private _empty?: boolean;
  private _errorChannel?: Map<string | null, any> | null;
  private _id?: string | null;
  private _replyChannel?: Map<string | null, any> | null;
  private _timestamp?: number | null;
  private _additionalProperties?: Map<string, Map<string, any>>;

  constructor(input: {
    empty?: boolean;
    errorChannel?: Map<string | null, any> | null;
    id?: string | null;
    replyChannel?: Map<string | null, any> | null;
    timestamp?: number | null;
    additionalProperties?: Map<string, Map<string, any>>;
  }) {
    this._empty = input.empty;
    this._errorChannel = input.errorChannel;
    this._id = input.id;
    this._replyChannel = input.replyChannel;
    this._timestamp = input.timestamp;
    this._additionalProperties = input.additionalProperties;
  }

  get empty(): boolean | undefined {
    return this._empty;
  }
  set empty(empty: boolean | undefined) {
    this._empty = empty;
  }

  get errorChannel(): Map<string | null, any> | null | undefined {
    return this._errorChannel;
  }
  set errorChannel(errorChannel: Map<string | null, any> | null | undefined) {
    this._errorChannel = errorChannel;
  }

  get id(): string | null | undefined {
    return this._id;
  }
  set id(id: string | null | undefined) {
    this._id = id;
  }

  get replyChannel(): Map<string | null, any> | null | undefined {
    return this._replyChannel;
  }
  set replyChannel(replyChannel: Map<string | null, any> | null | undefined) {
    this._replyChannel = replyChannel;
  }

  get timestamp(): number | null | undefined {
    return this._timestamp;
  }
  set timestamp(timestamp: number | null | undefined) {
    this._timestamp = timestamp;
  }

  get additionalProperties(): Map<string, Map<string, any>> | undefined {
    return this._additionalProperties;
  }
  set additionalProperties(
    additionalProperties: Map<string, Map<string, any>> | undefined,
  ) {
    this._additionalProperties = additionalProperties;
  }
}

class Message {
  private _headers?: MessageHeaders;
  private _payload?: string;
  private _additionalProperties?: Map<string, any>;

  constructor(input: {
    headers?: MessageHeaders;
    payload?: string;
    additionalProperties?: Map<string, any>;
  }) {
    this._headers = input.headers;
    this._payload = input.payload;
    this._additionalProperties = input.additionalProperties;
  }

  get headers(): MessageHeaders | undefined {
    return this._headers;
  }
  set headers(headers: MessageHeaders | undefined) {
    this._headers = headers;
  }

  get payload(): string | undefined {
    return this._payload;
  }
  set payload(payload: string | undefined) {
    this._payload = payload;
  }

  get additionalProperties(): Map<string, any> | undefined {
    return this._additionalProperties;
  }
  set additionalProperties(additionalProperties: Map<string, any> | undefined) {
    this._additionalProperties = additionalProperties;
  }
}

class CloseStatus {
  private _code?: number;
  private _reason?: string | null;
  private _additionalProperties?: Map<string, any>;

  constructor(input: {
    code?: number;
    reason?: string | null;
    additionalProperties?: Map<string, any>;
  }) {
    this._code = input.code;
    this._reason = input.reason;
    this._additionalProperties = input.additionalProperties;
  }

  get code(): number | undefined {
    return this._code;
  }
  set code(code: number | undefined) {
    this._code = code;
  }

  get reason(): string | null | undefined {
    return this._reason;
  }
  set reason(reason: string | null | undefined) {
    this._reason = reason;
  }

  get additionalProperties(): Map<string, any> | undefined {
    return this._additionalProperties;
  }
  set additionalProperties(additionalProperties: Map<string, any> | undefined) {
    this._additionalProperties = additionalProperties;
  }
}

class SessionConnectEvent {
  private _message?: Message;
  private _source?: Map<string, any>;
  private _timestamp?: number;
  private _user?: Principal;
  private _additionalProperties?: Map<string, any>;

  constructor(input: {
    message?: Message;
    source?: Map<string, any>;
    timestamp?: number;
    user?: Principal;
    additionalProperties?: Map<string, any>;
  }) {
    this._message = input.message;
    this._source = input.source;
    this._timestamp = input.timestamp;
    this._user = input.user;
    this._additionalProperties = input.additionalProperties;
  }

  get message(): Message | undefined {
    return this._message;
  }
  set message(message: Message | undefined) {
    this._message = message;
  }

  get source(): Map<string, any> | undefined {
    return this._source;
  }
  set source(source: Map<string, any> | undefined) {
    this._source = source;
  }

  get timestamp(): number | undefined {
    return this._timestamp;
  }
  set timestamp(timestamp: number | undefined) {
    this._timestamp = timestamp;
  }

  get user(): Principal | undefined {
    return this._user;
  }
  set user(user: Principal | undefined) {
    this._user = user;
  }

  get additionalProperties(): Map<string, any> | undefined {
    return this._additionalProperties;
  }
  set additionalProperties(additionalProperties: Map<string, any> | undefined) {
    this._additionalProperties = additionalProperties;
  }
}

class Principal {
  private _reservedName?: string;
  private _additionalProperties?: Map<string | null, any> | null;

  constructor(input: {
    reservedName?: string;
    additionalProperties?: Map<string | null, any> | null;
  }) {
    this._reservedName = input.reservedName;
    this._additionalProperties = input.additionalProperties;
  }

  get reservedName(): string | undefined {
    return this._reservedName;
  }
  set reservedName(reservedName: string | undefined) {
    this._reservedName = reservedName;
  }

  get additionalProperties(): Map<string | null, any> | null | undefined {
    return this._additionalProperties;
  }
  set additionalProperties(
    additionalProperties: Map<string | null, any> | null | undefined,
  ) {
    this._additionalProperties = additionalProperties;
  }
}

class SessionDisconnectEvent {
  private _closeStatus?: CloseStatus;
  private _message?: Message;
  private _sessionId?: string;
  private _source?: Map<string, any>;
  private _timestamp?: number;
  private _user?: Principal;
  private _additionalProperties?: Map<string, any>;

  constructor(input: {
    closeStatus?: CloseStatus;
    message?: Message;
    sessionId?: string;
    source?: Map<string, any>;
    timestamp?: number;
    user?: Principal;
    additionalProperties?: Map<string, any>;
  }) {
    this._closeStatus = input.closeStatus;
    this._message = input.message;
    this._sessionId = input.sessionId;
    this._source = input.source;
    this._timestamp = input.timestamp;
    this._user = input.user;
    this._additionalProperties = input.additionalProperties;
  }

  get closeStatus(): CloseStatus | undefined {
    return this._closeStatus;
  }
  set closeStatus(closeStatus: CloseStatus | undefined) {
    this._closeStatus = closeStatus;
  }

  get message(): Message | undefined {
    return this._message;
  }
  set message(message: Message | undefined) {
    this._message = message;
  }

  get sessionId(): string | undefined {
    return this._sessionId;
  }
  set sessionId(sessionId: string | undefined) {
    this._sessionId = sessionId;
  }

  get source(): Map<string, any> | undefined {
    return this._source;
  }
  set source(source: Map<string, any> | undefined) {
    this._source = source;
  }

  get timestamp(): number | undefined {
    return this._timestamp;
  }
  set timestamp(timestamp: number | undefined) {
    this._timestamp = timestamp;
  }

  get user(): Principal | undefined {
    return this._user;
  }
  set user(user: Principal | undefined) {
    this._user = user;
  }

  get additionalProperties(): Map<string, any> | undefined {
    return this._additionalProperties;
  }
  set additionalProperties(additionalProperties: Map<string, any> | undefined) {
    this._additionalProperties = additionalProperties;
  }
}
