/**
 * Placeholder chat data for the static chat page.
 *
 * THIS IS THE FILE TO REPLACE when wiring real data. Every component under
 * `app/(app)/chat/` is presentational and imports only the types below, so
 * swapping this module and changing `page.tsx`'s data source is the whole job -
 * no component needs restructuring.
 *
 * TODO(stomp): delete this file once real data lands. The work it stands in
 * for, in order:
 *   1. Friends come from the paginated `GET /friends` endpoint via
 *      `openapi-fetch` and the generated types in `app/types/api.d.ts` - never
 *      a hand-written fetch.
 *   2. Message history needs a REST endpoint; STOMP delivers only new
 *      messages, so an empty socket subscription shows an empty conversation.
 *      Confirm that endpoint exists before starting.
 *   3. Live messages arrive over STOMP via `react-stomp-hooks`; see
 *      `app/hooks/useChat.ts` (currently fully commented out).
 *   4. `CURRENT_USER_ID` is replaced by the real id - see its own note below.
 *   5. Keep `ChatMessage` and `Friend` exported from wherever they land: the
 *      components import the *types* from here, and moving them is a rename
 *      pass, not a redesign.
 */

/**
 * Mirrors `SendMessageEventResponse` in `app/types/asyncapi.d.ts` (generated by
 * @asyncapi/modelina - do not hand-edit that file; regenerate it instead).
 *
 * We cannot type fixtures with the generated class directly: it stores data in
 * private fields (`_content`, `_senderId`, ...), and private members make a
 * class type *nominal* in TypeScript. A structurally identical object literal
 * is therefore not assignable to it.
 *
 * On the wire every field is optional. These fixtures make them required so the
 * static page has nothing to guard; real data will need `?? ''` fallbacks at
 * the render boundary. That asymmetry is intentional and belongs to the wiring
 * task, not to this branch.
 *
 * TODO(stomp): decide where optionality is resolved. Recommended: normalise
 * once at the data boundary into this required shape, so components never
 * carry `?? ''` noise. If instead the optional generated type is passed
 * through, every field read in MessageBubble/Conversation needs a guard -
 * `messageId` especially, since it is the React `key` and `undefined` there
 * silently breaks list reconciliation rather than throwing.
 */
export type ChatMessage = {
  content: string;
  messageId: string;
  senderId: string;
  /** Pre-formatted for display by the backend, e.g. "9:12 AM". */
  time: string;
};

/**
 * Presence (`online`) is a placeholder for the separate presence channel
 * (`CheckPresenceRequest` in `app/hooks/usePresence.ts`), not for the chat
 * feed. Whoever wires this up should expect two sources, not one.
 *
 * TODO(stomp): this type flattens three sources that update independently -
 * identity (`GET /friends`), presence (`online`, presence channel) and a
 * derived label (`status`). Expect to split it: a friend record from REST,
 * merged with a presence map keyed by id. `status` is presentation, not data -
 * derive it ("Online" / "Last seen ...") rather than storing it, or it will
 * drift out of sync with `online` the moment presence updates alone.
 */
export type Friend = {
  id: string;
  name: string;
  /** Shown by `Avatar` when there is no image. */
  initial: string;
  /** Avatar fill; a CSS colour because it is per-friend runtime data. */
  color: string;
  online: boolean;
  /** Sub-line under the name in the conversation header. */
  status: string;
};

/**
 * Stands in for the authenticated user's id. Message direction is derived by
 * comparing this against `senderId` - there is no direction flag on the wire.
 *
 * TODO(stomp): read the real id from the `user_id` cookie, the way
 * `app/(app)/layout.tsx` already does, and thread it down from `page.tsx`
 * rather than importing a module-level constant. Note the failure mode is
 * silent: a wrong id throws no error, it just renders every bubble on the
 * wrong side. Worth an assertion or a fallback when it is absent.
 */
export const CURRENT_USER_ID = 'me';

export const friends: Friend[] = [
  {
    id: 'grzes',
    name: 'Grzegorz Nowak',
    initial: 'G',
    color: '#146b7a',
    online: true,
    status: 'Online',
  },
  {
    id: 'marta',
    name: 'Marta Kowalska',
    initial: 'M',
    color: '#2f9bcf',
    online: true,
    status: 'Online',
  },
  {
    id: 'ondrej',
    name: 'Ondrej Novak',
    initial: 'O',
    color: '#4ac9a0',
    online: false,
    status: 'Last seen 2 hours ago',
  },
  {
    id: 'amine',
    name: 'Amine Belkacem',
    initial: 'A',
    color: '#0d2b47',
    online: true,
    status: 'Online',
  },
  {
    id: 'sofia',
    name: 'Sofia Lindqvist',
    initial: 'S',
    color: '#7c8a92',
    online: false,
    status: 'Last seen yesterday',
  },
];

export const messagesByFriendId: Record<string, ChatMessage[]> = {
  grzes: [
    {
      messageId: 'grzes-1',
      senderId: 'grzes',
      content: 'Hey! Are you up for a match later?',
      time: '9:12 AM',
    },
    {
      messageId: 'grzes-2',
      senderId: CURRENT_USER_ID,
      content: 'Definitely. Give me an hour to finish this module.',
      time: '9:14 AM',
    },
    {
      messageId: 'grzes-3',
      senderId: 'grzes',
      content: 'Perfect. I will warm up in the meantime.',
      time: '9:15 AM',
    },
    {
      messageId: 'grzes-4',
      senderId: CURRENT_USER_ID,
      content: 'Fair warning: I have been practising my backhand.',
      time: '9:16 AM',
    },
    {
      messageId: 'grzes-5',
      senderId: 'grzes',
      content: 'That is what you said last time, and you lost 11-3.',
      time: '9:17 AM',
    },
  ],
  marta: [
    {
      messageId: 'marta-1',
      senderId: 'marta',
      content: 'Did the tournament bracket get published yet?',
      time: '8:40 AM',
    },
    {
      messageId: 'marta-2',
      senderId: CURRENT_USER_ID,
      content: 'Not yet, they said this afternoon.',
      time: '8:45 AM',
    },
  ],
  ondrej: [
    {
      messageId: 'ondrej-1',
      senderId: 'ondrej',
      content: 'Thanks for the review, I pushed the fixes.',
      time: 'Yesterday',
    },
  ],
  amine: [
    {
      messageId: 'amine-1',
      senderId: CURRENT_USER_ID,
      content: 'Are you joining the evening session?',
      time: '7:58 AM',
    },
    {
      messageId: 'amine-2',
      senderId: 'amine',
      content: 'Yes, I will be there around eight.',
      time: '8:02 AM',
    },
  ],
  sofia: [
    {
      messageId: 'sofia-1',
      senderId: 'sofia',
      content: 'Good game earlier!',
      time: 'Monday',
    },
  ],
};
