spring:
  application:
    name: transcend-backend
  jpa:
    properties:
      hibernate:
        default_schema: prod
    hibernate:
      ddl-auto: validate
server:
  port: 8000

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
springwolf:
  enabled: false 