spring:
  application:
    name: transcend-backend-dev
  sql:
    init:
      mode: always
      data-locations: classpath:data-dev.sql
  jpa:
    properties:
      hibernate:
        default_schema: dev
    hibernate:
      ddl-auto: validate
server:
  port: 8080