spring:
  main:
    banner-mode: off
  allowed-profiles:
    - local
    - dev
    - prod
server:
  servlet:
    context-path: /

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

security:
  jwt:
    secret: LV2UPLQ2YXOIWh3swq4RcQWXjtwKPFuvG1z7I0dfgII=
    expiration-ms: 3600000