spring:
  application:
    name: transcend-backend-dev
  liquibase:
    enabled: true
    change-log: classpath:changelog/db.changelog-master.yaml
    default_schema: dev
  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate:
        default_schema: dev
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
      data-locations: classpath:data-dev.sql
server:
  port: 8080