spring:
  main:
    banner-mode: off
server:
  servlet:
    context-path: /

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/

security:
  jwt:
    secret: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
    expiration-ms: 3600000