spring:
  main:
    banner-mode: off
  allowed-profiles:
    - local
    - dev
    - prod
  security:
    validation:
      common-passwords: classpath:validation/common-passwords.txt
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

security:
  jwt:
    secret: LV2UPLQ2YXOIWh3swq4RcQWXjtwKPFuvG1z7I0dfgII=
    expiration-ms: 3600000