services:
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis-db
    env_file:
      - .env
    volumes:
      - redisdata:/data
    ports:
      - "6380:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  redisdata:
    driver: local

networks:
  default:
    name: transcend-net
    driver: bridge
