name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Example env
        run: make env

      - name: Start infrastructure
        working-directory: infra
        run: make

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: backend/.gradle-docker-cache
          key: gradle-docker-${{ runner.os }}-${{ hashFiles('backend/transcend/build.gradle.kts') }}
          restore-keys: |
            gradle-docker-${{ runner.os }}-

      - name: Run PROD backend tests
        working-directory: backend
        run: |
          mkdir -p .gradle-docker-cache
          chmod -R 777 .gradle-docker-cache
          make test
      - name: Run DEV backend tests
        working-directory: backend
        run: |
          mkdir -p .gradle-docker-cache
          chmod -R 777 .gradle-docker-cache
          make -f Makefile.dev test